app/urls.py
from django.urls import path
from . import views

app_name = 'app'

urlpatterns = [
    path('', views.MonthlyList.as_view(), name='monthly_list'),
    path('add/', views.MonthlyAdd.as_view(), name='monthly_add'),
    path('update/<int:pk>/', views.monthly_update, name='monthly_update'),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
]

app/models.py
from django.db import models


class Monthly(models.Model):
    year = models.IntegerField('年')
    month = models.IntegerField('月')
    comment = models.TextField('月次に関するコメント', blank=True, null=True)

    class Meta:
        # 年と月の組み合わせは一意になるように。
        unique_together = ('year', 'month')

    def __str__(self):
        return f'{self.year}年{self.month}月'


class Daily(models.Model):
    day = models.IntegerField('日')
    month = models.ForeignKey(Monthly, verbose_name='紐づく年月', on_delete=models.PROTECT)

    # 予測値など、いろいろ作ってください。
    value = models.IntegerField('値', blank=True, null=True)

app/forms.py
from django import forms
from .models import Monthly, Daily


DailyInlineFormset = forms.inlineformset_factory(
    Monthly, Daily, exclude=['day'],  # 日にちは編集できないようにする
    extra=0, can_delete=False
)

# 一般的にはclass MonthlyForm のように作りますが、ちょっとしたものなら関数で作ることもできます。
MonthlyForm = forms.modelform_factory(Monthly, fields=['comment'])

app/views.py
import calendar
from django.views import generic
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse_lazy
from .forms import MonthlyForm, DailyInlineFormset
from .models import Monthly, Daily


class MonthlyList(generic.ListView):
    model = Monthly
    queryset = Monthly.objects.order_by('-year', '-month')  # 新しい月次から表示する


class MonthlyAdd(generic.CreateView):
    model = Monthly
    fields = '__all__'
    success_url = reverse_lazy('app:monthly_list')

    def form_valid(self, form):
        monthly = form.save()

        # その月が何日あるか取得
        days = calendar.monthlen(monthly.year, monthly.month)

        # 日付の数だけ日のデータを作成しておく
        for day in range(1, days+1):
            Daily.objects.create(month=monthly, day=day)

        return redirect('app:monthly_update', pk=monthly.pk)


def monthly_update(request, pk):
    monthly = get_object_or_404(Monthly, pk=pk)

    form = MonthlyForm(request.POST or None, instance=monthly)
    formset = DailyInlineFormset(request.POST or None, instance=monthly)

    if request.method == 'POST' and formset.is_valid() and form.is_valid():
        form.save()
        formset.save()
        # 編集ページを再度表示
        return redirect('app:monthly_list')

    context = {
        'form': form,
        'formset': formset
    }

    return render(request, 'app/monthly_form.html', context)

app/templates/app/base.html
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <title>たいとる</title>
</head>
<body>
{% block content %}{% endblock %}
</body>
</html>

app/templates/app/monthly_form.html
{% extends 'app/base.html' %}

{% block content %}
    <p><a href="{% url 'app:monthly_list' %}">月次リストへ</a></p>
    <form action="" method="POST">
        {{ form.as_p }}
        {{ formset.management_form }}
        {% for day_form in formset %}
            {% for field in day_form.hidden_fields %}
                {{ field }}
            {% endfor %}
            <p>
                {{ day_form.instance.day }}日: {{ day_form.value }}<!-- 29日: 入力欄 のようになる -->
            </p>
        {% endfor %}
        {% csrf_token %}
        <button type="submit">送信</button>
    </form>
{% endblock %}

app/templates/app/monthly_list.html
{% extends 'app/base.html' %}

{% block content  %}
    <p><a href="{% url 'app:monthly_add' %}">新しい月の作成</a></p>
    <h2>月次リスト</h2>
    {% for monthly in monthly_list %}
        <p><a href="{% url 'app:monthly_update' monthly.pk %}">{{ monthly }}</a></p>
    {% endfor %}
{% endblock %}